config/routes.rb
RailsApp::Application.routes.draw do
  devise_for :users

  resources :users,only: [:index]

  resources :subscriptions, only: [:index,:create,:destroy]

  resources :mangas, only: [:index,:create]

  resources :chapters, only: [:index,:create]

	
  get "/home/about" 
  get "/home/log" 
  get "/home/admin" 
  

  root :to => 'mangas#index'

end

app/models/manga.rb
class Manga < ActiveRecord::Base
  attr_accessible :display_name, :name
	has_many :chapters
	def last_chapter
		chapters.max_by{|c| c.nb ||= 0} 
	end
	def as_json(options = { })
    super((options || { }).merge({
        :methods => [:last_chapter_nb]
    }))
	end
	def last_chapter_nb
		chapters.map{|chapter| chapter.nb ||= 0}.max
	end

end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
	before_filter :out, :except=>[:index]
  # GET /mangas
  # GET /mangas.json
  def index
    @mangas = Manga.all.sort_by{|m| m.display_name}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mangas }
    end
  end

  # GET /mangas/1
  # GET /mangas/1.json
  def show
    @manga = Manga.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manga }
    end
  end

  # GET /mangas/new
  # GET /mangas/new.json
  def new
    @manga = Manga.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @manga }
    end
  end

  # GET /mangas/1/edit
  def edit
    @manga = Manga.find(params[:id])
  end

  # POST /mangas
  # POST /mangas.json
  def create
    @manga = Manga.new(params[:manga])

    respond_to do |format|
      if @manga.save
        format.html { render json: @manga, notice: 'Manga was successfully created.' }
        format.json { render json: @manga, status: :created, location: @manga }
      else
        format.html { render action: "new" }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mangas/1
  # PUT /mangas/1.json
  def update
    @manga = Manga.find(params[:id])

    respond_to do |format|
      if @manga.update_attributes(params[:manga])
        format.html { redirect_to @manga, notice: 'Manga was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @manga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mangas/1
  # DELETE /mangas/1.json
  def destroy
    @manga = Manga.find(params[:id])
    @manga.destroy

    respond_to do |format|
      format.html { redirect_to mangas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/views/mangas/_form.html.erb
<%= form_for(@manga) do |f| %>
  <% if @manga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manga.errors.count, "error") %> prohibited this manga from being saved:</h2>

      <ul>
      <% @manga.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mangas/_manga.html.erb
<tr>
		<%if false && user_signed_in? && current_user.is_admin? %>
    <td><%= manga.name %></td>
		<%end%>
    <td><%= manga.display_name %></td>
		<%if manga.chapters.any?%>
		<td><%=link_to manga.last_chapter.nb,manga.last_chapter.link,:class=>"btn btn-link",:title=>"Read Chapter",:data => {:toggle=>"tooltip"}%></td>
		<td><%=time_ago_in_words(manga.last_chapter.date) + " ago"%></td>
		<%else%>
		<td>No release</td>
		<td></td>
		<%end%>
	<%if user_signed_in? %>
		<%if !current_user.has_subscribe(manga)%>
			<td><%= link_to '', subscriptions_path(:manga_id=>manga.id),:method=>:post,:class=>"btn btn-primary glyphicon glyphicon-star",:title=>"Subscribe",:data => {:toggle=>"tooltip"} %></td>
	<%else%>
		<td><%= link_to '', subscription_path(Subscription.get(current_user,manga)),:confirm=>"Unsubscribe ?",:method=>:delete,:class=>"btn btn-default glyphicon glyphicon-remove",:title=>"Unsubscribe",:data => {:toggle=>"tooltip"}%></td>
	<%end%>
	<%end%>
  </tr>

app/views/mangas/edit.html.erb
<h1>Editing manga</h1>

<%= render 'form' %>

<%= link_to 'Show', @manga %> |
<%= link_to 'Back', mangas_path %>

app/views/mangas/index.html.erb
<h1>Last Releases</h1>

<table class="table table-striped table-bordered table-hover table-condensed">
  <tr>
		<%if false && user_signed_in? && current_user.is_admin? %>
    <th>MangaId</th>
		<%end%>
    <th>Manga</th>
    <th>Last release</th>
    <th>Time</th>
	<%if user_signed_in? %>
    <th>Action</th>
	<%end%>
  </tr>

<% @mangas.each do |manga| %>
				<%=render :partial=>"manga", :object=>manga%>
  <% end %>
</table>
<br />
<div class="alert alert-info">Looking for an other manga ? Contact me ! <a href="mailto:ste.luong@gmail.com">ste.luong@gmail.com</a></div>

app/views/mangas/new.html.erb
<h1>New manga</h1>

<%= render 'form' %>

<%= link_to 'Back', mangas_path %>

app/views/mangas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @manga.name %>
</p>

<p>
  <b>Display name:</b>
  <%= @manga.display_name %>
</p>


<%= link_to 'Edit', edit_manga_path(@manga) %> |
<%= link_to 'Back', mangas_path %>