config/routes.rb
RailsApp::Application.routes.draw do
  devise_for :users

  resources :users,only: [:index]

  resources :subscriptions, only: [:index,:create,:destroy]

  resources :mangas, only: [:index,:create]

  resources :chapters, only: [:index,:create]

	
  get "/home/about" 
  get "/home/log" 
  get "/home/admin" 
  

  root :to => 'mangas#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slapps | MRA</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap -->
	<link href="<%=%>" rel="stylesheet" media="screen">
</head>
<body>
<div id="wrap">
	<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
					<%= link_to "SLAPPS MRA",root_path, class:"navbar-brand"%>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
						<li <%if current_page? mangas_path%>class="active"<%end%>><%=link_to "Last Releases",mangas_path%></li>
						<li <%if current_page? subscriptions_path%>class="active"<%end%>><%=link_to user_signed_in? ? "Subscriptions":"Subscribe !",subscriptions_path%></li>
						<li <%if current_page? home_about_path%>class="active"<%end%>><%=link_to "About",home_about_path%></li>
						<%if user_signed_in? && current_user.is_admin? %>
						<li <%if current_page? home_about_path%>class="active"<%end%>><%=link_to "Log",home_log_path%></li>
				    <%end%>
          </ul>
					<ul class="nav navbar-nav navbar-right">
						<%if !user_signed_in?%>
						<li><%= link_to 'Log In', new_user_session_path %></li>
						<li><%= link_to "Sign Up",new_user_registration_path%></li>
						<%else%>
						<li>Logged as <%=current_user.email%></li>
						<li><%=link_to "Log Out",destroy_user_session_path,:method=>:delete%></li>
						<%end%>
					</ul>
        </div><!--/.nav-collapse -->
      </div>
		</div>
<div class="container">
	<%if notice%>
<div class="alert alert-info"><%= notice %></div>
		<%end%>
	<%if alert%>
<div class="alert alert-danger"><%= alert %></div>
		<%end%>
<%= yield %>
</div><!-- /.container -->
</div> <!-- /.wrap-->
<div id = "footer">
				<div class="container">
								<p class="credit"><a href="http://www.steven-luong.com">&copy; Steven Luong 2013</a></p>
	      </div>
</div>
<script>
	$(".container").tooltip({
		selector:"[data-toggle=tooltip]",
		placement:"right"
	});
</script>
</body>
</html>